### ISSUE TITLE
Correct documentation redirect on into-cps.org

### ISSUE THREAD

**Issue by clegaard** [INTO-CPS-Association/Documentation#8]
Currently this:
https://into-cps.org/documentation/

redirects to this:
https://into-cps-association.readthedocs.io/projects/desktop-application/en/latest/

should be:
https://into-cps-association.readthedocs.io/en/latest/

**Comment by CThuleHansen** [comment]
I will take care of this.

**Comment by clegaard** [comment]
Contacted Niklas who is unavailable for the next week or so.

**Comment by clegaard** [comment]
Redirect updated by Niklas
